import type { Metadata } from "next";
import { Nabla, Poppins, Righteous } from "next/font/google";
import "./globals.css";

const nabla = Nabla({
  variable: "--font-nabla",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const righteous = Righteous({
  variable: "--font-righteous",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${nabla.variable} ${righteous.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
